'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.36366
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Pdf.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _512px_Underline_font_awesome_svg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("512px-Underline_font_awesome.svg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Youtube -&gt; https://www.youtube.com/channel/UCZr2VGmXdJ-yGLUZztCVFGw
        '''
        '''Facebook -&gt; https://www.facebook.com/groups/AToZForLearningProgramming
        '''
        '''Twitter -&gt; https://twitter.com/SadikFattah
        '''
        '''Plus -&gt; https://plus.google.com/110268382009035036954
        '''
        '''Blogger -&gt; http://www.guercif.cf/.
        '''</summary>
        Friend ReadOnly Property _default() As String
            Get
                Return ResourceManager.GetString("_default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property align_justify_512() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("align_justify-512", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ceenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ceenter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Cocking() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Cocking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cyrillic_V() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cyrillic-V", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        '''&lt;html&gt;
        '''  &lt;head&gt;
        '''    &lt;title&gt;my project&lt;/title&gt; 
        '''	&lt;style tyle=&quot;text/css&quot;&gt;
        '''	*{
        '''padding: 0px;
        '''margin: 0px;
        '''}
        '''	&lt;/style&gt;
        '''   &lt;/head&gt;
        ''' &lt;body&gt;
        ''' &lt;p&gt; salam alikom&lt;/p&gt;
        ''' &lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property html() As String
            Get
                Return ResourceManager.GetString("html", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property internet_html() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("internet html", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Internet_web_browser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Internet-web-browser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property itextsharp() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("itextsharp", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property itextsharp_pdfa() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("itextsharp_pdfa", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property itextsharp_xtra() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("itextsharp_xtra", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to console.log &quot;Hello Welcome to Tutorials point&quot;.
        '''</summary>
        Friend ReadOnly Property js() As String
            Get
                Return ResourceManager.GetString("js", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property left_align() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("left-align", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to #!/usr/local/bin/lua
        '''
        '''print(&quot;Hello World!&quot;).
        '''</summary>
        Friend ReadOnly Property lua() As String
            Get
                Return ResourceManager.GetString("lua", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pdf_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pdf-A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?PHP
        '''
        '''
        '''
        '''?&gt;.
        '''</summary>
        Friend ReadOnly Property php() As String
            Get
                Return ResourceManager.GetString("php", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property right_align() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("right-align", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to   using System;
        '''
        '''   Namespace HelloWorldApplication\
        '''
        '''{
        '''    
        '''    Class HelloWorld
        '''
        '''{
        '''    
        '''    static void Main(string[] args)
        '''
        '''{
        '''    
        '''     Console.WriteLine(&apos;Hello World&apos;);
        '''
        '''     Console.ReadKey();
        '''
        '''}
        '''
        '''}
        '''
        '''}.
        '''</summary>
        Friend ReadOnly Property sharp() As String
            Get
                Return ResourceManager.GetString("sharp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property souligner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("souligner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [root@host]# mysqladmin -u root -p create TUTORIALS
        '''Enter password:******.
        '''</summary>
        Friend ReadOnly Property sql() As String
            Get
                Return ResourceManager.GetString("sql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property text_italic_xxl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text-italic-xxl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imports System
        '''Module Module1
        '''   &apos;This program will display Hello World 
        '''   Sub Main()
        '''      Console.WriteLine(&quot;Hello World&quot;)
        '''      Console.ReadKey()
        '''   End Sub
        '''End Module.
        '''</summary>
        Friend ReadOnly Property vb() As String
            Get
                Return ResourceManager.GetString("vb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        '''&lt;contact-info&gt;
        '''&lt;name&gt;Tanmay Patil&lt;/name&gt;
        '''&lt;company&gt;TutorialsPoint&lt;/company&gt;
        '''&lt;phone&gt;(011) 123-4567&lt;/phone&gt;
        '''&lt;/contact-info&gt;.
        '''</summary>
        Friend ReadOnly Property xml() As String
            Get
                Return ResourceManager.GetString("xml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property yellow_pdf_16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("yellow_pdf_16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
